import fs from 'fs';
import dotenv from 'dotenv';
import {defineConfig} from 'vite';
import {sveltekit} from '@sveltejs/kit/vite';

dotenv.config({
  path: '../.env'
});

const env = `# This file is generated by vite.config.ts

DEV=${process.env.APP_DEV}
API_SECRET=${process.env.APP_API_SECRET}
PUBLIC_API_URL=${process.env.APP_ORIGIN}
PUBLIC_APP_URL=${process.env.APP_ORIGIN}

# End of generated file
`;

fs.writeFileSync('./.env', env);

const host = process.env.APP_HOSTNAME ?? 'localhost';
const port = Number.parseInt(process.env.APP_DEV_PORT ?? '8080');

export default defineConfig({
  server: {
    host,
    port,
    hmr: {
      path: '/hmr'
    }
  },
  plugins: [sveltekit()]
});
