import fs from 'fs';
import dotenv from 'dotenv';
import {defineConfig} from 'vite';
import {sveltekit} from '@sveltejs/kit/vite';

dotenv.config({
  path: '../.env'
});

const hashBuffer = await crypto.subtle.digest(
  'SHA-256',
  new TextEncoder().encode(new Date().toISOString())
);
const hash =
  Buffer.from(hashBuffer).toString('hex').slice(0, 6) +
  Buffer.from(hashBuffer).toString('hex').slice(-6);

const env = `# This file is generated by vite.config.ts

DEV=${process.env.APP_DEV}
API_SECRET=${process.env.APP_API_SECRET}
PUBLIC_API_URL=${process.env.APP_ORIGIN}
PUBLIC_APP_URL=${process.env.APP_ORIGIN}
PUBLIC_BUILD=${hash}

# End of generated file
`;

fs.writeFileSync('./.env', env);

const host = process.env.APP_HOSTNAME ?? 'localhost';
const port = Number.parseInt(process.env.APP_DEV_PORT ?? '8080');

export default defineConfig({
  server: {
    host,
    port,
    hmr: {
      path: '/hmr'
    }
  },
  plugins: [sveltekit()],
  worker: {
    format: 'es'
  }
});
